plugins {
    id "net.fabricmc.fabric-loom" version "${loom_version}"
    id "maven-publish"
}

version = "${project.mod_version}+mc${project.minecraft_version}"
group = project.maven_group


repositories {
    // Add repositories to retrieve artifacts from in here.
    // You should only use this when depending on other mods because
    // Loom adds the essential maven repositories to download Minecraft and libraries from automatically.
    // See https://docs.gradle.org/current/userguide/declaring_repositories.html
    // for more information about repositories.
}

dependencies {
    // To change the versions see the gradle.properties file
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${project.loader_version}"

    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
}

processResources {
    inputs.property "version", project.version
    inputs.property "minecraft_version", project.minecraft_version
    inputs.property "loader_version", project.loader_version
    filteringCharset "UTF-8"

    filesMatching("fabric.mod.json") {
        expand "version": project.version,
                "minecraft_version": project.minecraft_version,
                "loader_version": project.loader_version
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 24
}

java {
    // Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task
    // if it is present.
    // If you remove this line, sources will not be generated.
    withSourcesJar()

    sourceCompatibility = JavaVersion.VERSION_24
    targetCompatibility = JavaVersion.VERSION_24
}

def generatedSrcDir = file("$buildDir/generated/buildinfo")
tasks.register("generateBuildInfo") {
    def commitHash = "unknown"
    def gitBranch = "unknown"
    def buildId = System.currentTimeMillis()
    def outputFile = new File(generatedSrcDir, "com/xkingdark/kingsveinminer/BuildInfo.java")

    try {
        commitHash = "git rev-parse --short HEAD".execute().text.trim()
    } catch (Exception ignored) {}
    try {
        gitBranch = "git branch --show-current".execute().text.trim()
    } catch (Exception ignored) {}

    outputs.file(outputFile)
    doLast {
        outputFile.parentFile.mkdirs()
        outputFile.text = """
            package com.xkingdark.kingsveinminer;
            
            public class BuildInfo {
                public static final String VERSION = "${project.mod_version}";
                public static final String BRANCH = "${gitBranch}";
                public static final String COMMIT_HASH = "${commitHash}";
                public static final String BUILD_ID = "${buildId}";
            };
        """.stripIndent()
    }
}

sourceSets.main.java.srcDir(generatedSrcDir)
tasks.named("compileJava") {
    dependsOn("generateBuildInfo")
}
afterEvaluate {
    tasks.named("sourcesJar") {
        dependsOn("generateBuildInfo")
    }
}

jar {
    def projectName = project.name
    inputs.property "projectName", projectName

    from("LICENSE") {
        rename { "${it}_${project.archives_base_name}" }
        rename { "${it}_$projectName"}
    }
}

// configure the maven publication
publishing {
    publications {
        create("mavenJava", MavenPublication) {
            artifactId = project.archives_base_name
            from components.java
        }
    }

    // See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
    repositories {
        // Add repositories to publish to here.
        // Notice: This block does NOT have the same function as the block in the top level.
        // The repositories here will be used for publishing your artifact, not for
        // retrieving dependencies.
    }
}
